image: <image_path>
tag: <image_tag>
namespace: "mgt-api"
service:
  name: management-api
  externalPort: 443
ingress:
  enabled: true
  # Used to create Ingress record (should used with service.type: ClusterIP).
  hosts: <management_api_desired_dns>
  serviceName: management-api
  servicePort: 443
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/secure-verify-ca-secret: ca-secret-ing-man-api
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  tls:
     secretName: tls-management-secret
     hosts: <management_api_desired_dns>
resources: {}
platformDomain: <dns_for_manager>
dexUrl: "https://dex.dex:443"
dexTokenPath: "/dex/token"
dexAuthPath: "/dex/auth"
platformAdmin: "platform_admin"
adminScope: "admin"
ingNamespace: 'ingress-nginx'
minio:
  secretCreate: true
  accessKey: <minio_access_key>
  secretKey: <minio_secret_key>
  endpoint: <minio_endpoint>
  endpointUrl: <minio_endpoint_url>
  minioRegion: "us-east-1"
  minioSignatureVersion: "s3v4"
dex:
  id: example-app
  redirectURIs: 'http://127.0.0.1:5555/callback'
  name: 'Example App'
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0
